[package]
name = "qvm"
version = "0.1.0"
authors = ["jwel <whdgnl1123@gmail.com>"]
description = "quantum computing simulator"
edition = "2018"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.2"
rand = "0.7"
